# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91de175f9cca28519336719d63adc36342fce871a30dee534a06a94d5d506f178db5ded22f0d51020f4157d278628f670e59207325a74219094ce8fb7c17055c

test:
  secret_key_base: 8b108e8d582b9a6e4dcdaf0a595b911a8dc425f1e546b17b0532310463acd484a23143fc1b9dadb8ac12c8ae0eb7cb29a6aa8d6219d502f5a97decce3f0a8b5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
